export const countries = [
  'Abkhazia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Albania',
  'Algeria',
  'Andorra',
  'Antarctica',
  'Argentina',
  'Armenia',
  'Afghanistan',
  'Bahamas',
  'Bangladesh',
  'Belarus',
  'Belgium',
  'Bermuda',
  'Bulgaria',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Brazil',
  'Hungary',
  'Venezuela',
  'Vietnam',
  'Haiti',
  'Guatemala',
  'Guinea',
  'Germany',
  'Hong Kong',
  'Greenland',
  'Greece',
  'Georgia',
  'Denmark',
  'Dominican Republic',
  'Egypt',
  'Zimbabwe',
  'Israel',
  'India',
  'Indonesia',
  'Jordan',
  'Iraq',
  'Iran',
  'Ireland',
  'Iceland',
  'Spain',
  'Italy',
  'Kazakhstan',
  'Canada',
  'Kenya',
  'Cyprus',
  'Kyrgyzstan',
  'China',
  'Colombia',
  'Korea',
  'Republic of Korea',
  'Cuba',
  'Kuwait',
  'Lao',
  'Latvia',
  'Lebanon',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Mauritius',
  'Madagascar',
  'Maldives',
  'Malta',
  'Morocco',
  'Mexico',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Namibia',
  'Nepal',
  'Niger',
  'Nigeria',
  'Netherlands',
  'Nicaragua',
  'New Zealand',
  'Norway',
  'United Arab Emirates',
  'Norfolk Island',
  'Pakistan',
  'Holy See (Vatican City State)',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Macedonia',
  'Russian Federation',
  'Romania',
  'San Marino',
  'Saudi Arabia',
  'Serbia',
  'Seychelles',
  'Singapore',
  'Syrian Arab Republic',
  'Slovakia',
  'Slovenia',
  'United Kingdom',
  'United States',
  'Somalia',
  'Sudan',
  'Sierra Leone',
  'Tajikistan',
  'Thailand',
  'Taiwan',
  'Tanzania',
  'Tunisia',
  'Turkmenistan',
  'Turkey',
  'Uganda',
  'Uzbekistan',
  'Ukraine',
  'Uruguay',
  'Fiji',
  'Philippines',
  'Finland',
  'Falkland Islands (Malvinas)',
  'France',
  'Croatia',
  'Central African Republic',
  'Chad',
  'Montenegro',
  'Czech Republic',
  'Chile',
  'Switzerland',
  'Sweden',
  'Sri Lanka',
  'Ecuador',
  'Estonia',
  'Ethiopia',
  'South Africa',
  'Jamaica',
  'Japan'];
